[project]
name = "mental-wealth-ambition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "pypdf2>=3.0.1",
    "streamlit>=1.51.0",
    "xlsxwriter>=3.2.9",
]
